service: identity-service
frameworkVersion: '3'

plugins:
  - serverless-offline
  
custom:
  tableName: 'identities-${sls:stage}'

provider:
  name: aws
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ IdentitiesTable, Arn ]
  environment:
    IDENTITIES_TABLE: ${self:custom.tableName}

functions:
  api:
    handler: dist/controllers/identity_controller.identityController
    events:
      - httpApi: '*'

resources:
  Resources:
    IdentitiesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
